#!/bin/bash
# file-protect.sh — PreToolUse hook for Write/Edit
# Prevents modifications to sensitive files like .env, credentials, and configs.
#
# Protected patterns:
# - .env files (all variants)
# - Credential/secret files
# - SSH keys
# - Lock files (package-lock.json, yarn.lock, etc.)
# - .git/ internals

INPUT=$(cat)
FILE_PATH=$(echo "$INPUT" | jq -r '.tool_input.file_path // empty')

if [ -z "$FILE_PATH" ]; then
  exit 0
fi

# Get just the filename
FILENAME=$(basename "$FILE_PATH")
FILEPATH_LOWER=$(echo "$FILE_PATH" | tr '[:upper:]' '[:lower:]')

# --- Block: .env files ---
if echo "$FILENAME" | grep -qE '^\.env(\..+)?$'; then
  echo "Blocked: .env files contain secrets and should not be modified by AI. Edit manually." >&2
  exit 2
fi

# --- Block: Credential files ---
if echo "$FILENAME" | grep -qiE '^(credentials|secrets|\.credentials|\.secrets)\.(json|yaml|yml|toml|xml)$'; then
  echo "Blocked: Credential files should not be modified by AI. Edit manually." >&2
  exit 2
fi

# --- Block: SSH keys ---
if echo "$FILEPATH_LOWER" | grep -qE '\.ssh/(id_|authorized_keys|known_hosts|config)'; then
  echo "Blocked: SSH configuration files should not be modified by AI." >&2
  exit 2
fi

# --- Block: .git internals ---
if echo "$FILEPATH_LOWER" | grep -qE '/\.git/'; then
  echo "Blocked: .git internals should not be modified directly." >&2
  exit 2
fi

# --- Warn: Lock files ---
if echo "$FILENAME" | grep -qiE '^(package-lock\.json|yarn\.lock|pnpm-lock\.yaml|Gemfile\.lock|poetry\.lock|Cargo\.lock|go\.sum|composer\.lock)$'; then
  jq -n '{
    hookSpecificOutput: {
      hookEventName: "PreToolUse",
      permissionDecision: "ask",
      permissionDecisionReason: "Lock files are auto-generated by package managers. Manual edits can cause dependency resolution issues."
    }
  }'
  exit 0
fi

# --- Warn: CI/CD configs ---
if echo "$FILEPATH_LOWER" | grep -qE '\.(github|gitlab|circleci)/'; then
  jq -n '{
    hookSpecificOutput: {
      hookEventName: "PreToolUse",
      permissionDecision: "ask",
      permissionDecisionReason: "CI/CD configuration changes can affect deployment pipelines. Please review carefully."
    }
  }'
  exit 0
fi

# All checks passed
exit 0
